version: '2'
services:
    chidren-app:
        image: chidren
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://chidren-mariadb:3306/chidren
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 4321:4321
    chidren-mariadb:
        extends:
            file: mariadb.yml
            service: chidren-mariadb
